[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
anchor_counter = "QGNoR7STSfkJufq1NQNyZUZjdXFtk6J5xW3suAW4apx"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/vishu9011/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
